import {seatedTabby} from './tabby-seat';
import {animateTabby} from './tabby-motion';
import {animateCatIdle} from './cat-idle';
import {registerMaterial} from './studio';
import {arrangement,type CatModel,type Pose} from './sculpture';
export type Placement=ReturnType<typeof arrangement>[number];
export type Spark={x:number;y:number;z:number;size:number;color:number;alpha:number;kind:'cube'|'mist'|'flash'};
export function world(p:Placement,v:number[]){const r=p.matrix;return {x:p.x+(r[0]*v[0]+r[1]*v[1]+r[2]*v[2])*p.scale,y:p.y+(r[3]*v[0]+r[4]*v[1]+r[5]*v[2])*p.scale,z:p.z+(r[6]*v[0]+r[7]*v[1]+r[8]*v[2])*p.scale};}
export function installLiquid(model:CatModel){
 // Named anchors describe the interior independently of the bottle's overall bounds.
 const c=model.center??[0,0,0],anchor=model.anchors?.Liquid_Pivot,circular=!!anchor,centerX=anchor?.[0]??-c[0],centerZ=anchor?.[2]??-c[2],bottom=model.anchors?.Liquid_Bottom_Pivot?.[1]??(.25-c[1]),level=anchor?.[1]??(1.87-c[1]),radius=circular?Math.abs(model.anchors!.Liquid_Radius_Pivot[0]-centerX):.955,width=radius*2,depth=circular?width:.79,ceiling=model.anchors?.Liquid_Ceiling_Pivot?.[1]??(level+.5),maxSlope=Math.min(.48,(ceiling-level-.05)/Math.max(radius,depth/2)),segments=80,rings=14;
 const p:number[]=[],n:number[]=[],idx:number[]=[],start=model.positions.length/3;
 for(let ring=0;ring<=rings;ring++)for(let i=0;i<=segments;i++){const a=i/segments*Math.PI*2,r=ring/rings,power=circular?1:.43,x=Math.sign(Math.cos(a))*Math.pow(Math.abs(Math.cos(a)),power)*width/2*r,z=Math.sign(Math.sin(a))*Math.pow(Math.abs(Math.sin(a)),power)*depth/2*r;p.push(x+centerX,level,z+centerZ);n.push(0,1,0);if(ring<rings&&i<segments){const k=ring*(segments+1)+i;idx.push(k,k+1,k+segments+1,k+1,k+segments+2,k+segments+1);}}
 const surfaceCount=p.length/3,outer=rings*(segments+1),sideTop=p.length/3;
 for(let i=0;i<=segments;i++){const x=p[(outer+i)*3]-centerX,z=p[(outer+i)*3+2]-centerZ,l=Math.hypot(x,z);p.push(x+centerX,level,z+centerZ);n.push(x/l,0,z/l);}
 const count=p.length/3,sideBottom=p.length/3;
 for(let i=0;i<=segments;i++){const x=p[(outer+i)*3]-centerX,z=p[(outer+i)*3+2]-centerZ,l=Math.hypot(x,z);p.push(x*(circular?.98:.91)+centerX,bottom,z*(circular?.98:.80)+centerZ);n.push(x/l,0,z/l);if(i<segments)idx.push(sideTop+i,sideTop+i+1,sideBottom+i+1,sideTop+i,sideBottom+i+1,sideBottom+i);}
 const floor=p.length/3;for(let i=0;i<=segments;i++){p.push(p[(sideBottom+i)*3],bottom,p[(sideBottom+i)*3+2]);n.push(0,-1,0);}
 const floorCenter=p.length/3;p.push(centerX,bottom,centerZ);n.push(0,-1,0);for(let i=0;i<segments;i++)idx.push(floor+i,floor+i+1,floorCenter);
 const pp=new Float32Array(model.positions.length+p.length);pp.set(model.positions);pp.set(p,model.positions.length);model.positions=pp;if(model.colors){const cc=new Float32Array(pp.length).fill(1);cc.set(model.colors);model.colors=cc;}
 const nn=new Float32Array(model.normals.length+n.length);nn.set(model.normals);nn.set(n,model.normals.length);model.normals=nn;
 const ii=new Uint32Array(model.indices.length+idx.length);ii.set(model.indices);ii.set(idx.map(i=>i+start),model.indices.length);
 const material=registerMaterial({hex:circular?0xf1c7d2:0xd8aa59,metal:0,rough:.065,opacity:1,transmission:.48,ior:1.34});model.groups.push({start:model.indices.length,count:idx.length,material});model.indices=ii;model.liquid={start,count,surfaceCount,bottom,level,width,depth,centerX,centerZ,maxSlope};model.basePositions=model.positions.slice();model.baseNormals=model.normals.slice();
}
export function createDynamics(models:CatModel[]){if(models[4].variant==='tabby')seatedTabby(models[4]);let sx=0,sz=0,vx=0,vz=0,lastX=0,lastZ=0;return (pose:Pose,poses:Placement[])=>{
 const model=models[2],liquid=model.liquid,p=poses[2];
 if(liquid){const dt=Math.min(.035,Math.max(.001,pose.delta)),limit=liquid.maxSlope,targetX=Math.max(-limit,Math.min(limit,-p.matrix[3]/Math.max(.4,p.matrix[4]))),targetZ=Math.max(-limit,Math.min(limit,-p.matrix[5]/Math.max(.4,p.matrix[4])));vx+=(targetX-lastX)*5;vz+=(targetZ-lastZ)*5;lastX=targetX;lastZ=targetZ;vx+=((targetX-sx)*32-vx*4.5)*dt;vz+=((targetZ-sz)*32-vz*4.5)*dt;sx+=vx*dt;sz+=vz*dt;const slope=Math.hypot(sx,sz);if(slope>limit){sx*=limit/slope;sz*=limit/slope;}
  const pumpAge=pose.time-pose.events[2],press=pose.motion&&pumpAge>=0&&pumpAge<.5?.038*Math.sin(pumpAge/.5*Math.PI):0;for(const part of model.parts??[]){if(!/actuator|nozzle_rim|nozzle_orifice/i.test(part.name))continue;for(let i=part.start;i<part.start+part.count;i++)model.positions[i*3+1]=model.basePositions![i*3+1]-press;}
  const energy=pose.motion?Math.min(.035,.008+Math.hypot(vx,vz)*.025):0;for(let i=liquid.start;i<liquid.start+liquid.count;i++){const x=model.positions[i*3]-liquid.centerX,z=model.positions[i*3+2]-liquid.centerZ,wave=energy*Math.sin(x*6+pose.time*4.7)*Math.cos(z*8-pose.time*3.3);model.positions[i*3+1]=liquid.level+sx*x+sz*z+wave;if(i<liquid.start+liquid.surfaceCount){const nx=-sx-energy*6*Math.cos(x*6+pose.time*4.7)*Math.cos(z*8-pose.time*3.3),nz=-sz+energy*8*Math.sin(x*6+pose.time*4.7)*Math.sin(z*8-pose.time*3.3),l=Math.hypot(nx,1,nz);model.normals.set([nx/l,1/l,nz/l],i*3);}}
 }
 const cat=models[4],age=pose.time-pose.events[4];if(cat.variant==='tabby'){animateTabby(cat,pose,pose.motion&&age>=0&&age<2.7?sneezeMotion(age):undefined);return;}if(cat.basePositions&&cat.baseNormals){cat.positions.set(cat.basePositions);cat.normals.set(cat.baseNormals);for(const part of cat.parts??[]){if(!/Squint/.test(part.name))continue;const pivot=cat.anchors?.[/Eye_L/.test(part.name)?'Eye_Squint_Pivot_L':'Eye_Squint_Pivot_R'];if(pivot)for(let i=part.start;i<part.start+part.count;i++)cat.positions.set(pivot,i*3);}if(pose.motion&&age>=0&&age<2.7){const m=sneezeMotion(age),center=cat.center??[0,cat.height/2,0],headPivot=cat.anchors?.Head_Pivot??[0,1.10-center[1],-center[2]],pivot=headPivot[1],pivotZ=headPivot[2],eyeY=cat.anchors?.Eye_Pivot_L?.[1]??(1.466-center[1]),mouthY=cat.anchors?.Mouth_Pivot?.[1]??(1.252-center[1]),co=Math.cos(m.pitch),si=Math.sin(m.pitch),headShift=(m.squash-1)*cat.height*.45;
 for(const part of cat.parts??[]){const name=part.name.toLowerCase(),head=/head|ear|eye|lid|squint|nose|muzzle|cheek|whisker|mouth|tongue|chin|brow/i.test(name);for(let i=part.start;i<part.start+part.count;i++){let x=cat.basePositions[i*3],y=cat.basePositions[i*3+1],z=cat.basePositions[i*3+2],nx=cat.baseNormals[i*3],ny=cat.baseNormals[i*3+1],nz=cat.baseNormals[i*3+2];if(head){if(/eye_|lid/.test(name)&&!/brow/.test(name)){const eye=cat.anchors?.[/eye_l|pivot_l/.test(name)?'Eye_Pivot_L':'Eye_Pivot_R']??[x,eyeY,z],closed=Math.max(0,Math.min(1,(.40-m.eye)/.25));if(/squint/.test(name)){const crease=cat.anchors?.[/eye_l/.test(name)?'Eye_Squint_Pivot_L':'Eye_Squint_Pivot_R']??eye;x=crease[0]+(x-crease[0])*closed;y=crease[1]+(y-crease[1])*closed;z=crease[2]+(z-crease[2])*closed;}else{const scale=1-closed;x=eye[0]+(x-eye[0])*scale;y=eye[1]+(y-eye[1])*m.eye*scale;z=eye[2]+(z-eye[2])*scale;ny/=Math.max(.005,m.eye);}}if(/mouth_interior/.test(name)){const stretch=1+m.mouth*3;y=mouthY+(y-mouthY)*stretch;ny/=stretch;}if(/tongue/.test(name))y=(1.064-center[1])+(y-(1.064-center[1]))*(1+m.mouth*2)-m.mouth*.040;if(/chin/.test(name))y-=m.mouth*.068;const py=y-pivot,pz=z-pivotZ;y=pivot+py*co-pz*si+headShift;z=pivotZ+py*si+pz*co;const nny=ny*co-nz*si;nz=ny*si+nz*co;ny=nny;}else if(!/paw|toe/.test(name)){y=(y+cat.height/2)*m.squash-cat.height/2;ny/=m.squash;x*=1+(1-m.squash)*.20;}cat.positions.set([x,y,z],i*3);const l=Math.hypot(nx,ny,nz)||1;cat.normals.set([nx/l,ny/l,nz/l],i*3);}}}}

 animateCatIdle(cat,pose);
};}
const hash=(n:number)=>{const v=Math.sin(n*127.1+311.7)*43758.5453;return v-Math.floor(v);};
export function effects(pose:Pose,poses:Placement[],models:CatModel[]):Spark[]{const out:Spark[]=[];for(let i=0;i<5;i++){const age=pose.time-pose.events[i],p=poses[i],h=models[i].height;if(age<0||pose.events[i]<-999||(age>6&&i!==3))continue;const emit=(v:number[],size:number,color:number,alpha:number,kind:Spark['kind'])=>{const q=world(p,v);out.push({...q,size:size*p.scale,color,alpha,kind});};
 if(i===0&&age<.85&&pose.motion){const center=models[0].center??[0,0,0],lens=[.0085-center[0],-.0027-center[1],.03422-center[2]],shutter=Math.max(0,Math.sin((age-.45)/.28*Math.PI));if(age>.45&&age<.73)emit(lens,h*.18*shutter,0x0d1217,1,'mist');if(age>.60)emit(lens,h*.21,0xdfeaff,Math.pow(Math.max(0,1-(age-.60)/.25),3)*.32,'flash');}
 if(i===1&&age<1.8&&pose.motion){for(let k=0;k<42;k++){const a=k*2.39996,s=.75+hash(k)*1.1,t=age,v=[Math.cos(a)*s*t,.3+(.8+hash(k+70)*1.3)*t-1.25*t*t,Math.sin(a)*s*t];emit(v,.075*(1-t/2),[0x4c7c2f,0x83b94b,0xb4d779,0x38622a][k%4],1-t/1.8,'cube');}}
 if(i===2&&age<1.6&&pose.motion){const c=models[i].center??[0,0,0],nozzle=models[i].anchors?.Nozzle_Pivot??[-c[0],3.676-c[1],.25-c[2]],press=age<.5?.038*Math.sin(age/.5*Math.PI):0;for(let k=0;k<58;k++){const delay=hash(k)*.28,t=age-delay;if(t<0)continue;const spread=.15+t*.38,a=k*2.399;emit([nozzle[0]+Math.cos(a)*spread*t,nozzle[1]-press+Math.sin(a)*spread*t-.12*t*t,nozzle[2]+t*(1.8+hash(k+8))],.018+hash(k+3)*.016,0xd9c8ce,Math.max(0,(1-t/1.35)*.65),'mist');}}

 if(i===4&&age>.94&&age<1.65&&pose.motion){const t=age-.94,model=models[4],m=sneezeMotion(age),pivot=model.anchors?.Head_Pivot??[0,0,0],mouth=model.anchors?.Mouth_Pivot??[0,h*.15,h*.36],dy=mouth[1]-pivot[1],dz=mouth[2]-pivot[2],pitch=m.pitch*(model.variant==='tabby'?.8:1),y=pivot[1]+dy*Math.cos(pitch)-dz*Math.sin(pitch)+(m.squash-1)*(model.variant==='tabby'?.48:h*.45),z=pivot[2]+dy*Math.sin(pitch)+dz*Math.cos(pitch);for(let k=0;k<12;k++){const a=k*2.399;emit([mouth[0]+Math.cos(a)*t*.19,y+Math.sin(a)*t*.2-t*.20,z+t*.8],h*.007,0xdbe4e6,(1-t/.71)*.38,'mist');}}
 }return out;}

export function sneezeMotion(t:number){const keys=[[0,0,1,1,0],[.25,-.10,1.02,.85,.1],[.64,-.34,1.045,.30,.45],[.82,-.39,1.04,.08,.7],[.98,.58,.82,.045,1],[1.12,.28,.90,.06,.75],[1.28,.42,.87,.07,.8],[1.56,-.10,1.015,.32,.25],[2.15,.025,1,.95,0],[2.65,0,1,1,0]];let k=0;while(k<keys.length-2&&t>keys[k+1][0])k++;const a=keys[k],b=keys[k+1],f=Math.max(0,Math.min(1,(t-a[0])/(b[0]-a[0]))),u=f*f*(3-2*f);return {pitch:a[1]+(b[1]-a[1])*u,squash:a[2]+(b[2]-a[2])*u,eye:a[3]+(b[3]-a[3])*u,mouth:a[4]+(b[4]-a[4])*u};}
