import * as T from 'three';
import {overlayVertex} from './atmosphere';
export function sunPlacement(width:number,height:number){const compact=width/height<.85;return {x:width*(compact?.91:.935),y:Math.max(compact?106:125,height*.15),radius:compact?15:Math.max(20,Math.min(28,width*.018))};}
export function createSun(scene:T.Scene){
 const sphere=new T.SphereGeometry(1,48,32),material=new T.MeshBasicMaterial({color:0xffefbe,toneMapped:false}),disk=new T.Mesh(sphere,material);
 const plane=new T.PlaneGeometry(1,1),haloMaterial=new T.ShaderMaterial({transparent:true,depthWrite:false,toneMapped:false,uniforms:{uOpacity:{value:1}},vertexShader:overlayVertex,fragmentShader:'varying vec2 vUv;uniform float uOpacity;void main(){float r=length((vUv-.5)*2.);float a=exp(-r*r*9.)*(1.-smoothstep(.65,1.,r))*.25*uOpacity;gl_FragColor=vec4(1.,.79,.35,a);}'}),halo=new T.Mesh(plane,haloMaterial);
 scene.add(disk,halo);
 return {update(width:number,height:number,amount:number){const p=sunPlacement(width,height),f=height/(2*Math.tan(17*Math.PI/180)),depth=10,k=depth/f;disk.visible=halo.visible=amount>.002;disk.position.set((p.x-width/2)*k,(height/2-p.y)*k,-2);disk.scale.setScalar(p.radius*k);material.color.setRGB(1,.88+.08*(1-amount),.60+.25*(1-amount));material.transparent=true;material.opacity=amount;halo.position.copy(disk.position);halo.position.z-=.03;halo.scale.setScalar(p.radius*k*7);haloMaterial.uniforms.uOpacity.value=amount;},dispose(){scene.remove(disk,halo);sphere.dispose();plane.dispose();material.dispose();haloMaterial.dispose();}};
}
export function paintSun(ctx:CanvasRenderingContext2D,width:number,height:number,amount:number){if(amount<.002)return;const p=sunPlacement(width,height),ratio=ctx.canvas.width/width;ctx.save();ctx.scale(ratio,ratio);ctx.globalAlpha=amount;const halo=ctx.createRadialGradient(p.x,p.y,p.radius*.6,p.x,p.y,p.radius*3.5);halo.addColorStop(0,'#efc57430');halo.addColorStop(.4,'#efc57414');halo.addColorStop(1,'#efc57400');ctx.fillStyle=halo;ctx.fillRect(p.x-p.radius*3.5,p.y-p.radius*3.5,p.radius*7,p.radius*7);const core=ctx.createRadialGradient(p.x-p.radius*.22,p.y-p.radius*.22,0,p.x,p.y,p.radius);core.addColorStop(0,'#fffbed');core.addColorStop(.65,'#fff0bf');core.addColorStop(1,'#f2db9e');ctx.fillStyle=core;ctx.beginPath();ctx.arc(p.x,p.y,p.radius,0,Math.PI*2);ctx.fill();ctx.restore();}
