import * as T from 'three';
import {arrangement,paperPlacement,type CatModel,type Pose} from './sculpture';
import {studio,materials} from './studio';
import {effects} from './dynamics';
import {candleLight,flameFragment} from './flame';
import {createSun} from './sun';
import {smoothstep} from '../hero-progress';
import {overlayVertex,smokeFragment,heatFragment} from './atmosphere';
export function createWebGLRenderer(canvas:HTMLCanvasElement,context:WebGL2RenderingContext,compact:boolean,models:CatModel[]){
 const renderer=new T.WebGLRenderer({canvas,context,antialias:true,alpha:true,powerPreference:'high-performance'});renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1;renderer.setClearColor(0xffffff,0);renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;
 const scene=new T.Scene(),camera=new T.PerspectiveCamera(34,1,.1,30);camera.position.z=8;let width=1,height=1;
 const w=1024,h=512,data=new Float32Array(w*h*4);for(let y=0;y<h;y++)for(let x=0;x<w;x++){const phi=x/w*Math.PI*2-Math.PI,theta=y/h*Math.PI,c=studio(Math.sin(phi)*Math.sin(theta),Math.cos(theta),Math.cos(phi)*Math.sin(theta)),i=(y*w+x)*4;data.set([...c,1],i);}
 const hdr=new T.DataTexture(data,w,h,T.RGBAFormat,T.FloatType);hdr.mapping=T.EquirectangularReflectionMapping;hdr.needsUpdate=true;const pmrem=new T.PMREMGenerator(renderer),environment=pmrem.fromEquirectangular(hdr);scene.environment=environment.texture;hdr.dispose();pmrem.dispose();
 const palette=materials.map(m=>new T.MeshPhysicalMaterial({color:m.hex,vertexColors:true,metalness:m.metal,roughness:m.rough,clearcoat:m.coat??(m.kind==='lens'?.7:m.metal>.6?.18:0),clearcoatRoughness:.08,sheen:m.kind==='plush'?.35:m.kind==='soft'?.6:0,sheenColor:new T.Color(m.kind==='plush'?0x64707b:0xffead4),sheenRoughness:1,transmission:m.transmission??(m.glass?.95:0),transparent:!!m.glass,opacity:m.glass?.72:1,depthWrite:!m.glass,side:m.doubleSided?T.DoubleSide:T.FrontSide,thickness:m.glass?.12:.06,ior:m.ior??1.46,envMapIntensity:1}));
 const texturedMaterials:T.MeshPhysicalMaterial[]=[];
 const meshes=models.map((model,i)=>{const g=new T.BufferGeometry();g.setAttribute('position',new T.BufferAttribute(model.positions,3));g.setAttribute('normal',new T.BufferAttribute(model.normals,3));if(model.uvs)g.setAttribute('uv',new T.BufferAttribute(model.uvs,2));const colors=model.colors??new Float32Array(model.positions.length).fill(1);g.setAttribute('color',new T.BufferAttribute(colors,3));g.setIndex(new T.BufferAttribute(model.indices,1));for(const part of [...model.groups].sort((a,b)=>Number(!!materials[a.material].glass)-Number(!!materials[b.material].glass)))g.addGroup(part.start,part.count,part.material);const surface=palette.slice();for(const texture of model.textures??[]){const material=palette[texture.material].clone();material.map=texture.map;material.map.anisotropy=Math.min(8,renderer.capabilities.getMaxAnisotropy());material.vertexColors=false;if(texture.normalMap){material.normalMap=texture.normalMap;material.normalScale.set(.42,.42);}surface[texture.material]=material;texturedMaterials.push(material);}const m=new T.Mesh(g,surface);m.castShadow=i===3;m.receiveShadow=i===3;scene.add(m);return m;});
 const sphere=new T.SphereGeometry(1,10,8),cube=new T.BoxGeometry(1,1,1),sparks=Array.from({length:128},()=>{const m=new T.Mesh<T.BufferGeometry,T.MeshBasicMaterial>(sphere,new T.MeshBasicMaterial({transparent:true,depthWrite:false}));m.visible=false;scene.add(m);return m;});
 const sun=createSun(scene),key=new T.DirectionalLight(0xfff2db,2.3);key.position.set(4,6,6);scene.add(key);
 const front=new T.DirectionalLight(0xf5f9ff,1.15);front.position.set(-3,1,6);scene.add(front);
 const bounce=new T.DirectionalLight(0xfff8ec,.3);bounce.position.set(0,-3,4);scene.add(bounce);
 const fill=new T.HemisphereLight(0xf7faff,0xc8c3b6,.7);scene.add(fill);
 const candle=new T.PointLight(0xffa74f,0,8,2);candle.castShadow=true;candle.shadow.mapSize.set(compact?512:1024,compact?512:1024);candle.shadow.bias=-.0007;candle.shadow.normalBias=.012;candle.shadow.camera.near=.015;candle.shadow.camera.far=8;scene.add(candle);
 const flameGeometry=new T.PlaneGeometry(1,1),flameMaterial=new T.ShaderMaterial({transparent:true,depthWrite:false,toneMapped:false,uniforms:{uTime:{value:0},uIntensity:{value:0}},vertexShader:'varying vec2 vUv;void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:flameFragment});const flame=new T.Mesh(flameGeometry,flameMaterial);flame.renderOrder=10;scene.add(flame);
 const glowMaterial=new T.ShaderMaterial({transparent:true,depthWrite:false,blending:T.AdditiveBlending,toneMapped:false,uniforms:{uOpacity:{value:0}},vertexShader:'varying vec2 vUv;void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:'varying vec2 vUv;uniform float uOpacity;void main(){float r=length((vUv-.5)*2.);float a=exp(-r*r*9.)*uOpacity*(1.-smoothstep(.55,1.,r));gl_FragColor=vec4(1.,.24,.018,a);}'});const glow=new T.Mesh(flameGeometry,glowMaterial);glow.renderOrder=9;scene.add(glow);

 const smokeMaterial=new T.ShaderMaterial({transparent:true,depthWrite:false,uniforms:{uTime:{value:0},uAge:{value:99},uNight:{value:0}},vertexShader:overlayVertex,fragmentShader:smokeFragment});const smoke=new T.Mesh(flameGeometry,smokeMaterial);smoke.renderOrder=11;scene.add(smoke);
 const emberMaterial=new T.MeshBasicMaterial({color:0xf66b20,transparent:true,depthWrite:false}),ember=new T.Mesh(sphere,emberMaterial);scene.add(ember);
 const heatTarget=new T.WebGLRenderTarget(1,1,{type:renderer.extensions.has('EXT_color_buffer_float')?T.HalfFloatType:T.UnsignedByteType}),heatScene=new T.Scene(),heatCamera=new T.OrthographicCamera(-1,1,1,-1,0,1),heatMaterial=new T.ShaderMaterial({transparent:false,blending:T.NoBlending,depthWrite:false,uniforms:{uScene:{value:heatTarget.texture},uTip:{value:new T.Vector2()},uSize:{value:new T.Vector2(.05,.15)},uTime:{value:0},uStrength:{value:0}},vertexShader:overlayVertex,fragmentShader:heatFragment}),heatQuad=new T.Mesh(new T.PlaneGeometry(2,2),heatMaterial);heatScene.add(heatQuad);
 renderer.compile(scene,camera);renderer.compile(heatScene,heatCamera);
 return {resize(w:number,h:number,dpr:number){width=w;height=h;renderer.setPixelRatio(dpr);renderer.setSize(w,h,false);canvas.style.width=w+'px';canvas.style.height=h+'px';camera.aspect=w/h;camera.updateProjectionMatrix();heatTarget.setSize(Math.round(w*dpr),Math.round(h*dpr));},render(pose:Pose){const poses=arrangement(width,height,pose,models),night=pose.focus;if(models[5])poses.push(paperPlacement(poses[4],models[4],models[5],pose.paperReveal??0,pose.time,pose.motion));sun.update(width,height,(pose.entrance??1)*(1-night)*(1-smoothstep(.22,.7,pose.progress)));key.intensity=2.3*(1-night);front.intensity=1.15*(1-night);bounce.intensity=.3*(1-night);fill.intensity=.7*(1-night)+.055*night;fill.color.setHex(night>.5?0xffb778:0xf9fcff);[...palette,...texturedMaterials].forEach(m=>{m.envMapIntensity=1.1*(1-night)+.004*night;});
 for(let i=0;i<meshes.length;i++){const p=poses[i],mesh=meshes[i];mesh.visible=p.visibility>.003&&(i===3||night<.35)&&(i!==5||(pose.paperReveal??0)>.015);if(i===2||i===4){mesh.geometry.attributes.position.needsUpdate=true;mesh.geometry.attributes.normal.needsUpdate=true;}mesh.position.set(p.x,p.y,p.z);mesh.rotation.set(p.rx,p.ry,p.rz,'ZYX');mesh.scale.setScalar(p.scale);}
 const light=candleLight(pose,poses[3],models[3]);flame.visible=glow.visible=pose.candle||night>.015;flame.position.set(light.tip.x,light.tip.y+light.height*.43,light.tip.z+.005);flame.quaternion.copy(camera.quaternion);flame.scale.set(light.height*.74,light.height,1);flameMaterial.uniforms.uTime.value=pose.motion?pose.time:0;flameMaterial.uniforms.uIntensity.value=Math.min(1,light.intensity);glow.position.copy(flame.position);glow.quaternion.copy(camera.quaternion);glow.scale.setScalar(light.height*5);glowMaterial.uniforms.uOpacity.value=.20*night*light.intensity;candle.position.set(light.tip.x,light.tip.y+light.height*.36,light.tip.z);candle.intensity=light.intensity*night*2.8*light.powerScale;candle.visible=night>.01;

 const outAge=pose.candleOut===undefined?99:pose.time-pose.candleOut,smokeHeight=models[3].height*poses[3].scale*.27;smoke.visible=pose.motion&&!pose.candle&&outAge>=0&&outAge<3.2;smoke.position.set(light.tip.x,light.tip.y+smokeHeight*.5,light.tip.z+.018);smoke.scale.set(smokeHeight*.75,smokeHeight,1);smokeMaterial.uniforms.uTime.value=pose.time;smokeMaterial.uniforms.uAge.value=outAge;smokeMaterial.uniforms.uNight.value=night;ember.visible=smoke.visible&&outAge<1.7;ember.position.set(light.tip.x,light.tip.y,light.tip.z+.015);ember.scale.setScalar(smokeHeight*.009);emberMaterial.opacity=Math.max(0,1-outAge/1.7);
 const fx=night>.3?[]:effects(pose,poses,models);sparks.forEach((m,i)=>{const p=fx[i];m.visible=!!p;if(!p)return;m.geometry=p.kind==='cube'?cube:sphere;m.position.set(p.x,p.y,p.z);m.scale.setScalar(p.size);m.rotation.set(pose.time*.8+i,i*1.3,pose.time+i);m.material.color.setHex(p.color);m.material.opacity=p.alpha;m.material.blending=p.kind==='flash'?T.AdditiveBlending:T.NormalBlending;});
 if(pose.candle&&pose.motion&&!compact){const tip=new T.Vector3(light.tip.x,light.tip.y+light.height*.9,light.tip.z).project(camera);heatMaterial.uniforms.uTip.value.set(tip.x*.5+.5,tip.y*.5+.5);heatMaterial.uniforms.uTime.value=pose.time;heatMaterial.uniforms.uStrength.value=night;heatMaterial.uniforms.uSize.value.set(.035,.12);renderer.setRenderTarget(heatTarget);renderer.render(scene,camera);renderer.setRenderTarget(null);renderer.render(heatScene,heatCamera);}else renderer.render(scene,camera);
 },dispose(){meshes.forEach(m=>m.geometry.dispose());palette.forEach(m=>m.dispose());texturedMaterials.forEach(m=>{m.map?.dispose();m.normalMap?.dispose();m.dispose();});sphere.dispose();cube.dispose();sparks.forEach(m=>m.material.dispose());sun.dispose();smokeMaterial.dispose();emberMaterial.dispose();heatTarget.dispose();heatQuad.geometry.dispose();heatMaterial.dispose();flameGeometry.dispose();flameMaterial.dispose();glowMaterial.dispose();candle.shadow.map?.dispose();environment.dispose();renderer.dispose();}};
}
