'use client';
import {useEffect,useState} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Switch} from '@/components/ui/switch';
import {type Entry,type Asset} from './content';
import {X,Upload,ArrowUpRight,Plus} from 'lucide-react';
export default function Editor({entry,onClose,onSave}:{entry:Entry|null;onClose:()=>void;onSave:(e:Entry)=>void}){const [draft,setDraft]=useState<Entry|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[preview,setPreview]=useState(false);
 useEffect(()=>{setDraft(entry?{...entry,assets:[...entry.assets]}:null);setError('');setPreview(false);},[entry]);
 async function upload(file:File,cover=false){if(!draft)return;setBusy(true);setError('');try{if(file.size>20*1024*1024)throw Error('20MB 이하의 파일을 골라 주세요. 큰 영상은 링크로 연결할 수 있어요.');const form=new FormData();form.append('file',file);const r=await fetch('/api/uploads',{method:'POST',body:form});const data=await r.json() as Asset & {error?:string};if(!r.ok)throw Error(data.error||'업로드하지 못했어요.');setDraft(d=>d?cover?{...d,cover:data.url}:{...d,assets:[...d.assets,data]}:d);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function save(){if(!draft)return;setBusy(true);setError('');try{const r=await fetch('/api/entries',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(draft)});const data=await r.json() as {entry:Entry,error?:string};if(!r.ok)throw Error(data.error||'저장하지 못했어요.');onSave(data.entry);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <Dialog open={!!entry} onOpenChange={v=>{if(!v&&!busy)onClose();}}><DialogContent className="editor-dialog" showCloseButton={false}><div className="editor-top"><div><DialogTitle>기록 편집</DialogTitle><DialogDescription>WEEK {String(entry?.week??0).padStart(2,'0')} · {entry?.medium}</DialogDescription></div><button aria-label="편집 닫기" disabled={busy} onClick={onClose}><X/></button></div>{draft&&<><div className="editor-fields">{preview?<div className="editor-preview">{draft.cover&&<img src={draft.cover} alt="표지 미리보기"/>}<h2>{draft.title}</h2><p>{draft.subtitle}</p><div className="preview-body">{draft.body}</div></div>:<><label>제목<input value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})} maxLength={120}/></label><label>짧은 소개<input value={draft.subtitle} onChange={e=>setDraft({...draft,subtitle:e.target.value})} maxLength={200}/></label><label>본문<textarea value={draft.body} onChange={e=>setDraft({...draft,body:e.target.value})} rows={10} placeholder="이 작업으로 어떤 나를 소개하고 싶나요?" maxLength={50000}/></label><label>작업 링크<input type="url" value={draft.link} onChange={e=>setDraft({...draft,link:e.target.value})} placeholder="https://"/></label><div className="editor-upload-row"><label className="upload-control"><Upload size={18}/> 표지 이미지<input type="file" accept="image/jpeg,image/png,image/webp,image/gif" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f)upload(f,true);e.target.value='';}}/></label><label className="upload-control"><Plus size={18}/> 파일 첨부<input type="file" accept="image/jpeg,image/png,image/webp,image/gif,video/mp4,video/webm,audio/mpeg,audio/wav,audio/ogg,audio/mp4,application/pdf" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f)upload(f);e.target.value='';}}/></label></div><p className="field-note">이미지·음성·영상·PDF, 파일당 20MB. 큰 파일과 앱은 작업 링크로 연결하세요.</p>{draft.cover&&<div className="cover-preview"><img src={draft.cover} alt="선택한 표지"/><button onClick={()=>setDraft({...draft,cover:''})}>표지 제외</button></div>}{draft.assets.map((a,i)=><div className="attachment-item" key={a.url}><span>{a.name}</span><button aria-label={`${a.name} 첨부 제외`} onClick={()=>setDraft({...draft,assets:draft.assets.filter((_,n)=>n!==i)})}><X size={16}/></button></div>)}<div className="publish-switch"><div><label htmlFor="published">기록에 표시</label><p>끄면 준비 중으로 표시됩니다.</p></div><Switch id="published" checked={draft.published} onCheckedChange={v=>setDraft({...draft,published:v})}/></div></>}{error&&<p className="form-error" role="alert">{error}</p>}</div><div className="editor-footer"><button className="secondary-button" disabled={busy} onClick={()=>setPreview(!preview)}>{preview?'편집 계속':'미리보기'}</button><button className="save-button" disabled={busy||!draft.title.trim()} onClick={save}>{busy?'저장하는 중…':'저장하기'} <ArrowUpRight size={18}/></button></div></>}</DialogContent></Dialog>;
}
