'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import type {LoadReporter} from './use-intro-loading';
const tracks=['shutter','grass','spray','match','sneeze'];
const volume=[.35,.20,.22,.25,.37,.22];
function fireworkBuffer(ac:AudioContext){const buffer=ac.createBuffer(1,Math.floor(ac.sampleRate*.8),ac.sampleRate),data=buffer.getChannelData(0);let seed=731;for(let i=0;i<data.length;i++){const t=i/ac.sampleRate;seed=(1664525*seed+1013904223)>>>0;const noise=(seed/4294967296)*2-1,attack=Math.min(1,t/.003),body=Math.sin(2*Math.PI*(83*t-27*t*t))*Math.exp(-t*18),crackle=noise*Math.exp(-t*7)*(.15+.8*Math.max(0,Math.sin(t*123))**12);data[i]=attack*(body*.48+noise*Math.exp(-t*34)*.46+crackle*.25);}return buffer;}
export function useSiteAudio(onLoad?:LoadReporter,start=true){
 const loadRef=useRef(onLoad),startRef=useRef(start);loadRef.current=onLoad;startRef.current=start;
 const [sound,setSound]=useState(true),[musicError,setMusicError]=useState(false),audio=useRef<HTMLAudioElement|null>(null),enabled=useRef(true),context=useRef<AudioContext|null>(null),music=useRef<GainNode|null>(null),active=useRef(new Set<AudioBufferSourceNode>()),buffers=useRef<(AudioBuffer|null)[]>(Array(6).fill(null));enabled.current=sound;
 const resume=useCallback(()=>{if(!enabled.current||!startRef.current)return;const ac=context.current;void ac?.resume().catch(()=>{});if(ac&&music.current)music.current.gain.setTargetAtTime(active.current.size?.085:.18,ac.currentTime,.18);const piano=audio.current;if(piano&&piano.paused)void piano.play().catch(()=>{});},[]);
 useEffect(()=>{const ac=new AudioContext();context.current=ac;let disposed=false,musicUrl='';let completed=0;const settled=()=>{if(!disposed)loadRef.current?.('audio',++completed/6);};const gain=ac.createGain();gain.gain.value=.18;gain.connect(ac.destination);music.current=gain;const piano=audio.current;const source=piano?ac.createMediaElementSource(piano):null;source?.connect(gain);if(piano)piano.volume=1;
 tracks.forEach((name,i)=>{fetch('/audio/'+name+'.mp3').then(r=>{if(!r.ok)throw Error('Audio unavailable');return r.arrayBuffer();}).then(b=>ac.decodeAudioData(b)).then(buffer=>{if(!disposed)buffers.current[i]=buffer;}).catch(()=>{}).finally(settled);});
 fetch('/audio/gymnopedie-no-1.mp3').then(r=>{if(!r.ok)throw Error('Music unavailable');return r.blob();}).then(blob=>{if(disposed)return;musicUrl=URL.createObjectURL(blob);if(piano){piano.src=musicUrl;piano.load();}resume();}).catch(()=>{if(!disposed)setMusicError(true);}).finally(settled);
 resume();const gesture=()=>resume();const events=['pointerdown','pointerup','keydown','wheel','touchstart'] as const;events.forEach(type=>window.addEventListener(type,gesture,{capture:true}));return()=>{disposed=true;events.forEach(type=>window.removeEventListener(type,gesture,{capture:true}));piano?.pause();active.current.forEach(s=>{try{s.stop();}catch{}});active.current.clear();source?.disconnect();if(musicUrl)URL.revokeObjectURL(musicUrl);gain.disconnect();music.current=null;context.current=null;void ac.close();};},[resume]);
 useEffect(()=>{if(start)resume();},[start,resume]);
 const playEffect=useCallback((index:number,pan=0,distance=0)=>{if(!enabled.current)return;const ac=context.current;if(!ac||ac.state!=='running')return;if(index===5&&!buffers.current[5])buffers.current[5]=fireworkBuffer(ac);const buffer=buffers.current[index];if(!buffer||ac.state!=='running'||active.current.size>=4)return;const source=ac.createBufferSource(),gain=ac.createGain(),panner=ac.createStereoPanner();source.buffer=buffer;gain.gain.value=volume[index]*(1-Math.min(.5,Math.max(0,distance))*.4);panner.pan.value=Math.max(-.8,Math.min(.8,pan));source.connect(gain).connect(panner).connect(ac.destination);active.current.add(source);music.current?.gain.setTargetAtTime(.075,ac.currentTime,.055);source.onended=()=>{active.current.delete(source);source.disconnect();gain.disconnect();panner.disconnect();if(!active.current.size&&enabled.current&&ac.state!=='closed')music.current?.gain.setTargetAtTime(.18,ac.currentTime,.3);};source.start();},[]);
 const toggleSound=useCallback(()=>{if(enabled.current){enabled.current=false;audio.current?.pause();const ac=context.current;if(ac)music.current?.gain.setValueAtTime(0,ac.currentTime);active.current.forEach(source=>{try{source.stop();}catch{}});active.current.clear();setSound(false);}else{enabled.current=true;setSound(true);setMusicError(false);resume();}},[resume]);
 return {sound,audio,musicError,setMusicError,toggleSound,playEffect};
}
